// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaDz2ZEuok3NE_PBL5v-EXBRLW9XNmGy0',
    appId: '1:672437938650:web:e5027b7cf1fa79ad3e78e3',
    messagingSenderId: '672437938650',
    projectId: 'smash-b17db',
    authDomain: 'smash-b17db.firebaseapp.com',
    databaseURL: 'https://smash-b17db-default-rtdb.firebaseio.com',
    storageBucket: 'smash-b17db.appspot.com',
    measurementId: 'G-PSFJB9W22Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWio5z0wfltm3yQHRbsm0D3fXGpf8DYWI',
    appId: '1:672437938650:android:5976215d7242a6853e78e3',
    messagingSenderId: '672437938650',
    projectId: 'smash-b17db',
    databaseURL: 'https://smash-b17db-default-rtdb.firebaseio.com',
    storageBucket: 'smash-b17db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjmks7u-1mZza_HmxQY-OusR71Jh-tQLg',
    appId: '1:672437938650:ios:9ab4a9d09ebc2f703e78e3',
    messagingSenderId: '672437938650',
    projectId: 'smash-b17db',
    databaseURL: 'https://smash-b17db-default-rtdb.firebaseio.com',
    storageBucket: 'smash-b17db.appspot.com',
    iosBundleId: 'com.example.smashFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjmks7u-1mZza_HmxQY-OusR71Jh-tQLg',
    appId: '1:672437938650:ios:9ab4a9d09ebc2f703e78e3',
    messagingSenderId: '672437938650',
    projectId: 'smash-b17db',
    databaseURL: 'https://smash-b17db-default-rtdb.firebaseio.com',
    storageBucket: 'smash-b17db.appspot.com',
    iosBundleId: 'com.example.smashFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaDz2ZEuok3NE_PBL5v-EXBRLW9XNmGy0',
    appId: '1:672437938650:web:8f8461efffd9359e3e78e3',
    messagingSenderId: '672437938650',
    projectId: 'smash-b17db',
    authDomain: 'smash-b17db.firebaseapp.com',
    databaseURL: 'https://smash-b17db-default-rtdb.firebaseio.com',
    storageBucket: 'smash-b17db.appspot.com',
    measurementId: 'G-E4RDLK6W70',
  );

}